# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/welcome.ipynb
"""

origem = (0,0)
destino = (4,4)

enderecos = [(3,4), (2,2), (8, 3), (5, 3)]

rota = [origem] + enderecos + [destino]

import matplotlib.pyplot as plt

from scipy.spatial.distance import euclidean as distancia_euclidiana

tamanho_rota = len(rota)

distancia_percorrida = 0

for i in range(tamanho_rota):
    x, y = rota[i]
    cor = "black"
    if i == 0:
        cor = "blue"
    elif i == tamanho_rota - 1:
        cor = "red"

    plt.scatter(x, y, color=cor)
    if i < tamanho_rota - 1:
        x1, y1 = rota[i+1]
        dx = x1 - x
        dy = y1 - y
        plt.arrow(x, y, dx, dy, color="black", head_width=0.1)
        distancia_percorrida = distancia_percorrida + distancia_euclidiana(rota[i], rota[i+1])

print(distancia_percorrida)